### ISSUE TITLE
No such file or directory: '/path/.tusync_credentials'

### ISSUE THREAD

**Issue by azmove** [junessi/tusync#1]
你好 请问能否提供下tusync_credentials文件的模版
我这边尝试运行不了 缺少此文件
万分感谢
Command: [Errno 2] No such file or directory: '/Users/miss/.tusync_credentials'

**Comment by azmove** [comment]
还有这个错误
AsyncUpdater.update(): update_daily() missing 1 required positional argument: 'stock_code'

**Comment by junessi** [comment]
你好，.tusync_credentials模板已经添加，请参考READNME。另外bug已修复。

**Comment by junessi** [comment]
lost response, close.
